In [3]:
# importing libraries
import pandas as pd
import numpy as np

In [4]:
# loading dataset
df = pd.read_excel('E-commerce Customer Churn Dataset_Raw_Data.xlsx')

In [5]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            542 non-null    object
 1   Customer_Name          533 non-null    object
 2   Gender                 536 non-null    object
 3   Age                    536 non-null    float64
 4   State                  531 non-null    object
 5   City                   539 non-null    object
 6   Tenure_Months          534 non-null    float64
 7   Subscription_Type      530 non-null    object
 8   Monthly_Charges        529 non-null    float64
 9   Total_Charges          533 non-null    float64
 10  Contract_Type          538 non-null    object
 11  Payment_Method         526 non-null    object
 12  Internet_Service       535 non-null    object
 13  Tech_Support           530 non-null    object
 14  Senior_Citizen         534 non-null    object
 15  Dependents             539 non-null    object
 16  Churn                  538 non-null    object
 17  Last_Interaction_Date  539 non-null    object
dtypes: float64(4), object(14)
memory usage: 76.3+ KB

In [7]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  536.000000     534.000000       529.000000     533.000000
mean    44.399254      36.406367      1335.269206   49745.287336
std     18.556837      20.669599       715.972838   41644.111657
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       756.570000   18770.290000
50%     44.000000      38.000000      1306.800000   40649.600000
75%     57.000000      54.000000      1900.650000   75647.400000
max    165.000000      72.000000      2492.510000  171429.830000

In [8]:
df.isnull().sum()

Customer_ID               0
Customer_Name             9
Gender                    6
Age                       6
State                    11
City                      3
Tenure_Months             8
Subscription_Type        12
Monthly_Charges          13
Total_Charges             9
Contract_Type             4
Payment_Method           16
Internet_Service          7
Tech_Support             12
Senior_Citizen            8
Dependents                3
Churn                     4
Last_Interaction_Date     3
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(7)

In [10]:
df["Gender"].unique()

array(['Female', 'Male', ' male ', nan], dtype=object)

In [11]:
df["Contract_Type"].unique()

array(['One Year', 'Two Year', 'Month-to-Month', nan, 'Month-to-Month ',
       'One Year '], dtype=object)

In [12]:
df["Subscription_Type"].unique()

array(['basic', 'Premium', 'Basic', 'Standard', nan, 'BASIC', 'Premium ',
       'Basic ', 'Standard ', 'Premium  ', '  Basic'], dtype=object)

In [13]:
df["Payment_Method"].unique()

array(['UPI', 'Cash', 'Debit Card', nan, 'Credit Card', 'Net Banking',
       'Credit Card  '], dtype=object)

In [14]:
df["Internet_Service"].unique()

array(['Fiber', 'DSL', '5G', 'Cable', nan, 'DSL  '], dtype=object)

In [15]:
df["Tech_Support"].unique()

array(['Yes', 'No', nan], dtype=object)

In [16]:
df["Senior_Citizen"].unique()

array(['No', 'Yes', 'No ', nan], dtype=object)

In [17]:
df["Dependents"].unique()

array(['Yes', 'No', nan], dtype=object)

In [18]:
df["Churn"].unique()

array(['No', 'Yes', 'YES', 'yes', nan], dtype=object)

In [19]:
df[["Age", "Tenure_Months", "Monthly_Charges", "Total_Charges"]].describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  536.000000     534.000000       529.000000     533.000000
mean    44.399254      36.406367      1335.269206   49745.287336
std     18.556837      20.669599       715.972838   41644.111657
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       756.570000   18770.290000
50%     44.000000      38.000000      1306.800000   40649.600000
75%     57.000000      54.000000      1900.650000   75647.400000
max    165.000000      72.000000      2492.510000  171429.830000

In [20]:
df[(df["Age"] < 18) | (df["Age"] > 100)]

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
5,C1005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026
13,C1013,Neha Verma,Male,3.0,Gujarat,Surat,57.0,Premium,2143.68,122650.76,One Year,Debit Card,Cable,No,No,No,No,09-04-2025
16,C1016,Priya Gupta,Female,120.0,Karnataka,Mysuru,19.0,Standard,1295.83,24158.77,One Year,Net Banking,5G,No,No,Yes,Yes,12-01-2026
22,C1022,Pooja Singh,Male,4.0,Gujarat,Ahmedabad,70.0,Basic,1260.16,88678.20,One Year,Net Banking,DSL,No,No,No,Yes,27-06-2026
27,C1027,Rahul Singh,Male,5.0,UP,Kanpur,58.0,Premium,1441.72,84097.76,Month-to-Month,Credit Card,5G,Yes,No,No,No,12-06-2026
46,C1046,Sneha Jain,Female,140.0,Maharashtra,Pune,62.0,Basic,NaN,34002.48,Two Year,Cash,DSL,Yes,No,Yes,No,01-09-2025
75,C1075,Priya Gupta,Female,137.0,Maharashtra,Mumbai,66.0,Premium,700.29,45741.14,Month-to-Month,Debit Card,DSL,Yes,No,No,No,05-03-2026
122,C1122,Sneha Jain,Female,121.0,Gujarat,Ahmedabad,28.0,Basic,1295.88,35988.64,One Year,Net Banking,Cable,Yes,No,Yes,No,23-03-2025
202,C1202,Sneha Jain,Female,165.0,UP,Kanpur,60.0,Basic,449.41,26519.60,One Year,Cash,DSL,Yes,No,No,Yes,03-04-2025
537,C5005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026

In [21]:
df[(df["Monthly_Charges"] < 0)]

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
97,C1097,Rohit Kumar,Female,65.0,UP,Lucknow,60.0,Basic,-1042.36,62577.60,One Year,UPI,5G,Yes,Yes,Yes,No,30-01-2025
123,C1123,Amit Sharma,Female,28.0,Gujarat,Ahmedabad,57.0,Basic,-1621.45,92655.65,Month-to-Month,Cash,Cable,No,No,Yes,Yes,08-01-2026
126,C1126,Rahul Singh,Male,22.0,Delhi,Delhi,28.0,Standard,-680.31,-18976.68,One Year,Debit Card,Cable,NaN,No,No,Yes,08-12-2025
166,C1166,Rahul Singh,Female,22.0,Maharashtra,Mumbai,40.0,Basic,-1838.55,73086.00,One Year,Net Banking,Fiber,No,No,No,No,09-05-2026
217,C1217,Rohit Kumar,Female,20.0,UP,Lucknow,66.0,Standard,-2454.77,162302.82,One Year,Debit Card,DSL,Yes,No,Yes,Yes,25-04-2026
457,C1457,Anjali Mehta,Female,42.0,UP,Kanpur,29.0,Basic,-904.51,-25767.79,Month-to-Month,Net Banking,Cable,Yes,No,Yes,No,19-06-2026

In [22]:
df[(df["Total_Charges"] < 0)]

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
17,C1017,Abhishek Jaiswal,Female,NaN,Gujarat,Ahmedabad,48.0,Basic,1975.23,-94534.04,Month-to-Month,Credit Card,Fiber,NaN,No,No,No,13-08-2025
36,C1036,Rohit Kumar,Male,48.0,UP,Kanpur,70.0,Premium,1285.52,-89554.40,Month-to-Month,UPI,Cable,No,No,No,No,04-04-2025
94,C1094,Amit Sharma,Male,63.0,Maharashtra,Mumbai,43.0,Premium,2331.74,-99781.82,One Year,Cash,Fiber,No,Yes,No,No,19-12-2025
126,C1126,Rahul Singh,Male,22.0,Delhi,Delhi,28.0,Standard,-680.31,-18976.68,One Year,Debit Card,Cable,NaN,No,No,Yes,08-12-2025
457,C1457,Anjali Mehta,Female,42.0,UP,Kanpur,29.0,Basic,-904.51,-25767.79,Month-to-Month,Net Banking,Cable,Yes,No,Yes,No,19-06-2026

In [23]:
df["Last_Interaction_Date"] .head(10)

0    12-10-2025
1    05-03-2026
2    20-02-2026
3    07-06-2026
4    02-04-2026
5    13-03-2026
6    26-12-2025
7    14-01-2025
8    28-02-2025
9    29-11-2025
Name: Last_Interaction_Date, dtype: object

In [24]:
df["Last_Interaction_Date"].unique()

array(['12-10-2025', '05-03-2026', '20-02-2026', '07-06-2026',
       '02-04-2026', '13-03-2026', '26-12-2025', '14-01-2025',
       '28-02-2025', '29-11-2025', '03-10-2025', '32/13/2025',
       '27-09-2025', '09-04-2025', '05-10-2025', '01-01-2026',
       '12-01-2026', '13-08-2025', '04-06-2025', '05-07-2025',
       '27-03-2025', '26-03-2026', '27-06-2026', '22-01-2026',
       '06-03-2026', '29-04-2026', '12-06-2026', '17-08-2025',
       '02-08-2025', '16-01-2025', '26-06-2026', '25-04-2026',
       '04-01-2026', '18-04-2026', '07-12-2025', '04-04-2025',
       '21-09-2025', '17-07-2025', '16-10-2025', '29-01-2026',
       '01-06-2026', '06-10-2025', '16-11-2025', '01-09-2025',
       '21-01-2025', '25-01-2026', '17-05-2026', '21-01-2026',
       '31-01-2025', '03-03-2026', '18-01-2025', '06-06-2026',
       '24-03-2026', '11-06-2025', '27-04-2026', '13-04-2026',
       '28-02-2026', '07-02-2026', '13-06-2026', '12-02-2025',
       '25-02-2025', '03-06-2025', '01-05-2026', '23-05-2025',
       '16-02-2026', '15-04-2026', '30-04-2026', '26-03-2025',
       '11-03-2025', '14-08-2025', '27-02-2026', '01-12-2025',
       '16-06-2026', '11-01-2025', '30-03-2025', '19-10-2025',
       '06-06-2025', '04-07-2026', '13-03-2025', '20-08-2025',
       '27-04-2025', '29-01-2025', '29-10-2025', '07-05-2025',
       '09-06-2026', '05-08-2025', '19-12-2025', '23-02-2025',
       '30-01-2025', '15-02-2026', '06-04-2025', '16-02-2025',
       '18-09-2025', '20-11-2025', '29-09-2025', '17-02-2025',
       '18-02-2026', '20-10-2025', '21-02-2025', '13-07-2025',
       '28-11-2025', '15-09-2025', '17-09-2025', '25-02-2026',
       '03-03-2025', '09-06-2025', '04-05-2026', '19-02-2025',
       '03-07-2025', '23-03-2025', '08-01-2026', '24-01-2025',
       '02-05-2026', '08-12-2025', '09-03-2026', '25-05-2026',
       '04-02-2025', '19-03-2026', '28-12-2025', '07-02-2025',
       '01-11-2025', '30-06-2025', '14-07-2025', '23-11-2025',
       '19-04-2026', '26-01-2026', '10-01-2026', '10-07-2025',
       '10-04-2026', '29-12-2025', '17-11-2025', '16-07-2025',
       '06-08-2025', '15-02-2025', '18-08-2025', '28-01-2026',
       '21-03-2026', '05-06-2026', '22-02-2025', '12-02-2026',
       '02-02-2026', '08-03-2025', '09-05-2026', '06-09-2025',
       '24-04-2025', '02-01-2026', '13-10-2025', '06-12-2025',
       '03-05-2026', '26-10-2025', '24-04-2026', '04-08-2025',
       '30-04-2025', '27-12-2025', '28-07-2025', '22-09-2025',
       '24-08-2025', '28-01-2025', '10-03-2026', '14-04-2026',
       '22-06-2025', '11-05-2025', '19-03-2025', '28-06-2026',
       '13-05-2026', '08-07-2025', '18-05-2026', '16-03-2026',
       '02-03-2025', '28-08-2025', '26-11-2025', '03-04-2025',
       '02-11-2025', '07-09-2025', '10-08-2025', '04-04-2026',
       '13-02-2025', '17-01-2025', '24-11-2025', '21-05-2026',
       '18-12-2025', '02-06-2025', '14-02-2025', '29-04-2025',
       '10-06-2025', '26-06-2025', '10-01-2025', '18-03-2025',
       '31-08-2025', '21-11-2025', '06-04-2026', '17-06-2025',
       '04-06-2026', '03-09-2025', '20-03-2026', '13-01-2025',
       '08-09-2025', '18-11-2025', '04-01-2025', '27-08-2025',
       '07-06-2025', '01-02-2026', '30-11-2025', '22-12-2025',
       '23-03-2026', '25-03-2025', '26-02-2026', '15-06-2025',
       '19-09-2025', '01-01-2025', '27-05-2026', '29-08-2025',
       '10-12-2025', '23-08-2025', '15-12-2025', '08-08-2025',
       '30-03-2026', '04-03-2025', '17-06-2026', '15-01-2025',
       '03-01-2025', '11-04-2025', '09-11-2025', '01-07-2025',
       '16-01-2026', '08-04-2026', '23-04-2025', '01-02-2025',
       '12-03-2026', '10-05-2026', '31-07-2025', '22-03-2026',
       '15-08-2025', '16-09-2025', '03-01-2026', '06-05-2025',
       '28-03-2025', '13-01-2026', '11-01-2026', '23-04-2026',
       '12-11-2025', '21-04-2026', '03-02-2026', '24-12-2025',
       '02-12-2025', '26-01-2025', '16-05-2025', '27-06-2025',
       '17-05-2025', '29-03-2025', '21-10-2025', '30-08-2025',
       '27-02-2025', '18-04-2025', '07-11-2025', '26-04-2026',
       '31-10-2025', '10-10-2025', '23-02-2026', '23-07-2025',
       '22-07-2025', '08-04-2025', '25-03-2026', '17-10-2025',
       '12-06-2025', '03-08-2025', '29-05-2026', '24-06-2026',
       '17-04-2025', '01-08-2025', '07-04-2025', '22-10-2025',
       '18-02-2025', '13-05-2025', '06-01-2026', nan, '10-02-2025',
       '25-06-2026', '14-04-2025', '28-04-2025', '16-05-2026',
       '10-02-2026', '20-05-2025', '19-07-2025', '15-11-2025',
       '29-05-2025', '15-03-2026', '03-06-2026', '31-12-2025',
       '11-11-2025', '18-07-2025', '10-11-2025', '05-11-2025',
       '19-01-2026', '08-06-2025', '03-12-2025', '02-05-2025',
       '12-07-2025', '03-02-2025', '08-11-2025', '27-05-2025',
       '24-02-2026', '17-01-2026', '19-02-2026', '11-10-2025',
       '29-06-2025', '24-03-2025', '19-06-2026', '12-05-2025',
       '31-05-2026', '28-10-2025', '21-06-2026', '14-11-2025',
       '26-09-2025', '30-05-2026', '21-02-2026', '31-01-2026',
       '15-07-2025', '30-10-2025', '06-05-2026', '13-12-2025',
       '15-04-2025', '11-02-2025', '30-09-2025', '30-05-2025',
       '30-01-2026', '18-01-2026', '08-10-2025', '02-02-2025',
       '21-06-2025', '07-10-2025', '25-01-2025', '06-03-2025'],
      dtype=object)

In [25]:
df[df["Customer_ID"].duplicated(keep=False)].sort_values("Customer_ID")

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
18,C1018,Amit Sharma,NaN,41.0,Gujarat,Ahmedabad,48.0,Premium,2328.32,111299.36,Month-to-Month,Net Banking,Fiber,Yes,No,Yes,No,04-06-2025
524,C1018,Anikta Sharma,Female,41.0,Gujarat,Ahmedabad,48.0,Premium,2328.32,111299.36,Month-to-Month,Net Banking,Fiber,Yes,No,Yes,No,04-06-2025
531,C1018,Anikta Sharma,Female,41.0,Gujarat,Ahmedabad,48.0,Premium,2328.32,111299.36,Month-to-Month,Net Banking,Fiber,Yes,No,Yes,No,04-06-2025
518,C1518,Vikas Yadav,Male,47.0,Maharashtra,Pune,1.0,Premium,2473.81,2618.81,One Year,Cash,NaN,No,No,NaN,Yes,NaN
525,C1518,Vikas Yadav,Male,47.0,Maharashtra,Pune,1.0,Premium,2473.81,2618.81,One Year,Cash,NaN,No,No,NaN,Yes,NaN
519,C1519,NaN,Male,52.0,Karnataka,Bengaluru,39.0,Premium,718.22,27823.58,Month-to-Month,NaN,Fiber,Yes,No,Yes,No,11-02-2025
526,C1519,NaN,Male,52.0,Karnataka,Bengaluru,39.0,Premium,718.22,27823.58,Month-to-Month,NaN,Fiber,Yes,No,Yes,No,11-02-2025
520,C1520,Pooja Singh,Male,69.0,UP,Lucknow,NaN,Premium,687.44,NaN,Month-to-Month,Debit Card,Fiber,Yes,Yes,Yes,No,21-11-2025
527,C1520,Pooja Singh,Male,69.0,UP,Lucknow,NaN,Premium,687.44,NaN,Month-to-Month,Debit Card,Fiber,Yes,Yes,Yes,No,21-11-2025
521,C1521,Mohit Arora,NaN,54.0,NaN,Bengaluru,1.0,NaN,NaN,1705.68,NaN,Net Banking,Fiber,Yes,No,Yes,NaN,10-01-2025
528,C1521,Mohit Arora,NaN,54.0,NaN,Bengaluru,1.0,NaN,NaN,1705.68,NaN,Net Banking,Fiber,Yes,No,Yes,NaN,10-01-2025
522,C1522,Mohit Arora,Female,49.0,UP,Kanpur,43.0,Premium,2140.60,92290.80,Month-to-Month,Net Banking,DSL,NaN,NaN,Yes,Yes,15-08-2025
529,C1522,Mohit Arora,Female,49.0,UP,Kanpur,43.0,Premium,2140.60,92290.80,Month-to-Month,Net Banking,DSL,NaN,NaN,Yes,Yes,15-08-2025
523,C1523,Sneha Jain,Male,36.0,Karnataka,Bengaluru,27.0,Standard,2436.13,65686.51,One Year,Debit Card,DSL,Yes,No,No,No,23-03-2025
530,C1523,Sneha Jain,Male,36.0,Karnataka,Bengaluru,27.0,Standard,2436.13,65686.51,One Year,Debit Card,DSL,Yes,No,No,No,23-03-2025

In [26]:
df["Customer_ID"].isnull().sum()

np.int64(0)

In [27]:
df.groupby("Gender")["Age"].median()

Gender
 male     26.0
Female    42.0
Male      45.5
Name: Age, dtype: float64

In [28]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [29]:
df_clean = df.copy()

In [30]:
# Removing WhiteSpaces

In [31]:
df_clean["Gender"] = df_clean["Gender"].str.strip()

In [32]:
df_clean["State"] = df_clean["State"].str.strip()

In [33]:
df_clean["Contract_Type"] = df_clean["Contract_Type"].str.strip()

In [34]:
df_clean["Subscription_Type"] = df_clean["Subscription_Type"].str.strip()

In [35]:
df_clean["Payment_Method"] = df_clean["Payment_Method"].str.strip()

In [36]:
df_clean["Internet_Service"] = df_clean["Internet_Service"].str.strip()

In [37]:
df_clean["Tech_Support"] = df_clean["Tech_Support"].str.strip()

In [38]:
df_clean["Senior_Citizen"] = df_clean["Senior_Citizen"].str.strip()

In [39]:
df_clean["Dependents"] = df_clean["Dependents"].str.strip()

In [40]:
df_clean["Churn"] = df_clean["Churn"].str.strip()

In [41]:
# Removing Inconsistent values / Standard capitization

In [42]:
df_clean["Gender"] = df_clean["Gender"].replace({
    "male" : "Male",
    "FeMale" : "Female"
})

In [43]:
df_clean["Subscription_Type"] = df_clean["Subscription_Type"].replace({
    "basic" : "Basic",
    "BASIC" : "Basic"
})

In [44]:
df_clean["Churn"] = df_clean["Churn"].replace({
    "YES" : "Yes",
    "yes" : "Yes"
})

In [45]:
df_clean["Dependents"].unique()

array(['Yes', 'No', nan], dtype=object)

In [46]:
# Missing Values

In [47]:
df_clean["Customer_Name"] = df_clean["Customer_Name"].fillna("Unknown")

In [48]:
df_clean["Customer_Name"].isna().sum()

np.int64(0)

In [49]:
df_clean[df_clean["State"].isna()][["Customer_ID", "City", "State"]]

    Customer_ID       City State
25        C1025      Delhi   NaN
108       C1108  Ahmedabad   NaN
113       C1113       Pune   NaN
148       C1148  Bengaluru   NaN
160       C1160      Noida   NaN
177       C1177  Ahmedabad   NaN
420       C1420      Surat   NaN
473       C1473      Surat   NaN
509       C1509      Surat   NaN
521       C1521  Bengaluru   NaN
528       C1521  Bengaluru   NaN

In [50]:
city_state_mapping = df_clean.groupby("City")["State"].first()

In [51]:
df_clean["State"] = df_clean["State"].fillna(df_clean["City"].map(city_state_mapping))

In [52]:
df_clean["State"].isna().sum()

np.int64(0)

In [53]:
# Cheaking for the city-state mapping

In [54]:
df_clean[df_clean["City"].isna()][
    ["Customer_ID", "State", "City"]
]

    Customer_ID  State City
31        C1031     UP  NaN
147       C1147  Delhi  NaN
437       C1437     UP  NaN

In [55]:
df_clean[df_clean["City"].isna()][
    ["Customer_ID", "Customer_Name", "Gender", "Age",
     "State", "Tenure_Months", "Subscription_Type",
     "Monthly_Charges", "Total_Charges",
     "Contract_Type", "Payment_Method",
     "Internet_Service", "Churn"]
]

,Customer_ID,Customer_Name,Gender,Age,State,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Churn
31,C1031,Abhishek Jaiswal,Male,37.0,UP,23.0,Premium,1555.38,35431.74,One Year,Debit Card,Fiber,Yes
147,C1147,Vikas Yadav,NaN,62.0,Delhi,42.0,Basic,2492.51,104747.42,Month-to-Month,Net Banking,Fiber,No
437,C1437,Sneha Jain,Female,56.0,UP,2.0,Premium,873.54,1712.08,Month-to-Month,NaN,5G,No

In [56]:
df_clean["City"] = df_clean["City"].fillna("Unknown")

In [57]:
# Cheaking Age columns

In [58]:
df_clean.loc[df_clean["Age"] < 18, "Age"] = np.nan

In [59]:
df_clean.loc[df_clean["Age"] > 100, "Age"] = np.nan

In [60]:
df_clean["Age"].describe()

count    526.000000
mean      43.484791
std       15.435357
min       18.000000
25%       30.000000
50%       43.500000
75%       56.000000
max       70.000000
Name: Age, dtype: float64

In [61]:
df_clean["Age"].isna().sum()

np.int64(16)

In [62]:
df_clean["Age"].median()

np.float64(43.5)

In [63]:
df_clean.groupby("Gender")["Age"].median()

Gender
Female    42.0
Male      46.0
Name: Age, dtype: float64

In [64]:
df_clean[df_clean["Age"].isna()][
    ["Customer_ID", "Gender", "Age"]
]

    Customer_ID  Gender  Age
1         C1001    Male  NaN
5         C1005  Female  NaN
11        C1011    Male  NaN
13        C1013    Male  NaN
16        C1016  Female  NaN
17        C1017  Female  NaN
22        C1022    Male  NaN
27        C1027    Male  NaN
46        C1046  Female  NaN
75        C1075  Female  NaN
78        C1078  Female  NaN
122       C1122  Female  NaN
202       C1202  Female  NaN
306       C1306    Male  NaN
533       C5001    Male  NaN
537       C5005  Female  NaN

In [65]:
gender_age_median = df_clean.groupby("Gender")["Age"].transform("median")

In [66]:
gender_age_median.head(20)

0     42.0
1     46.0
2     42.0
3     46.0
4     46.0
5     42.0
6     42.0
7     46.0
8     46.0
9     46.0
10    46.0
11    46.0
12    42.0
13    46.0
14    46.0
15    46.0
16    42.0
17    42.0
18     NaN
19    46.0
Name: Age, dtype: float64

In [67]:
df_clean["Age"] = df_clean["Age"].fillna(gender_age_median)

In [68]:
df_clean["Age"].isnull().sum()

np.int64(0)

In [69]:
df_clean["Age"]

0      35.0
1      46.0
2      42.0
3      59.0
4      26.0
       ...
537    42.0
538    18.0
539    61.0
540    45.0
541    25.0
Name: Age, Length: 542, dtype: float64

In [70]:
# Tenure Month

In [71]:
df_clean["Tenure_Months"].describe()

count    534.000000
mean      36.406367
std       20.669599
min        1.000000
25%       19.000000
50%       38.000000
75%       54.000000
max       72.000000
Name: Tenure_Months, dtype: float64

In [72]:
df_clean[df_clean["Tenure_Months"] <= 0][["Customer_ID", "Tenure_Months"]]

Empty DataFrame
Columns: [Customer_ID, Tenure_Months]
Index: []

In [73]:
df_clean.groupby("Contract_Type")["Tenure_Months"].median()

Contract_Type
Month-to-Month    42.0
One Year          38.0
Two Year          32.0
Name: Tenure_Months, dtype: float64

In [74]:
df_clean[df_clean["Tenure_Months"].isna()][
    ["Customer_ID", "Contract_Type", "Subscription_Type", "Churn"]
]

    Customer_ID   Contract_Type Subscription_Type Churn
145       C1145  Month-to-Month           Premium   Yes
178       C1178  Month-to-Month           Premium    No
257       C1257        Two Year          Standard    No
274       C1274        One Year             Basic   Yes
331       C1331  Month-to-Month          Standard   Yes
400       C1400        Two Year             Basic    No
520       C1520  Month-to-Month           Premium    No
527       C1520  Month-to-Month           Premium    No

In [75]:
contract_tenure_median = df_clean.groupby("Contract_Type")["Tenure_Months"].transform("median")

In [76]:
contract_tenure_median

0      38.0
1      32.0
2      42.0
3      32.0
4      38.0
       ...
537    32.0
538    42.0
539    38.0
540    32.0
541    42.0
Name: Tenure_Months, Length: 542, dtype: float64

In [77]:
df_clean["Tenure_Months"] = df_clean["Tenure_Months"].fillna(contract_tenure_median)

In [78]:
df_clean["Tenure_Months"].isna().sum()

np.int64(0)

In [79]:
# Monthly Charges - dealing with negative values

In [80]:
df_clean[df_clean["Monthly_Charges"] < 0][
    ["Customer_ID", "Age", "Tenure_Months", "Subscription_Type",
     "Monthly_Charges", "Total_Charges", "Contract_Type", "Churn"]
]

,Customer_ID,Age,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Churn
97,C1097,65.0,60.0,Basic,-1042.36,62577.60,One Year,No
123,C1123,28.0,57.0,Basic,-1621.45,92655.65,Month-to-Month,Yes
126,C1126,22.0,28.0,Standard,-680.31,-18976.68,One Year,Yes
166,C1166,22.0,40.0,Basic,-1838.55,73086.00,One Year,No
217,C1217,20.0,66.0,Standard,-2454.77,162302.82,One Year,Yes
457,C1457,42.0,29.0,Basic,-904.51,-25767.79,Month-to-Month,No

In [81]:
df_clean["Monthly_Charges"].describe()

count     529.000000
mean     1335.269206
std       715.972838
min     -2454.770000
25%       756.570000
50%      1306.800000
75%      1900.650000
max      2492.510000
Name: Monthly_Charges, dtype: float64

In [82]:
df_clean["Monthly_Charges"] = df_clean["Monthly_Charges"].abs()

In [83]:
df_clean[df_clean["Monthly_Charges"] < 0][
    ["Customer_ID", "Monthly_Charges"]
]

Empty DataFrame
Columns: [Customer_ID, Monthly_Charges]
Index: []

In [84]:
df_clean["Monthly_Charges"].describe()

count     529.000000
mean     1367.563913
std       652.046459
min       302.540000
25%       764.880000
50%      1341.520000
75%      1908.060000
max      2492.510000
Name: Monthly_Charges, dtype: float64

In [85]:
# dealing with empty values

In [86]:
df_clean.groupby("Subscription_Type")["Monthly_Charges"].median()

Subscription_Type
Basic       1294.530
Premium     1357.755
Standard    1285.780
Name: Monthly_Charges, dtype: float64

In [87]:
df_clean[df_clean["Monthly_Charges"].isna()][
    ["Customer_ID", "Subscription_Type", "Contract_Type",
     "Internet_Service", "Tenure_Months", "Total_Charges"]
]

,Customer_ID,Subscription_Type,Contract_Type,Internet_Service,Tenure_Months,Total_Charges
3,C1003,Standard,Two Year,5G,55.0,101349.10
46,C1046,Basic,Two Year,DSL,62.0,34002.48
81,C1081,Standard,Month-to-Month,Fiber,66.0,131972.34
117,C1117,Premium,Month-to-Month,5G,62.0,135306.04
142,C1142,Premium,Month-to-Month,DSL,29.0,55925.61
173,C1173,Basic,One Year,5G,68.0,24100.64
178,C1178,Premium,Month-to-Month,Fiber,42.0,35932.36
221,C1221,Basic,Two Year,Cable,68.0,57917.76
263,C1263,Basic,Two Year,Cable,25.0,60679.25
420,C1420,Basic,One Year,DSL,5.0,6605.80
521,C1521,NaN,NaN,Fiber,1.0,1705.68
528,C1521,NaN,NaN,Fiber,1.0,1705.68
535,C5003,Standard,Two Year,5G,55.0,101349.10

In [88]:
subscription_monthly_median = df_clean.groupby(
    "Subscription_Type"
)["Monthly_Charges"].transform("median")

In [89]:
df_clean["Monthly_Charges"] = df_clean["Monthly_Charges"].fillna(
    subscription_monthly_median
)

In [90]:
# dealing with these two values with nan

In [91]:
df_clean[df_clean["Monthly_Charges"].isna()][
    ["Customer_ID", "Subscription_Type", "Monthly_Charges"]
]

    Customer_ID Subscription_Type  Monthly_Charges
521       C1521               NaN              NaN
528       C1521               NaN              NaN

In [92]:
(df_clean["Total_Charges"] / df_clean["Tenure_Months"]).describe()

count     533.000000
mean     1345.956964
std       712.428330
min     -2320.507442
25%       755.315455
50%      1321.160000
75%      1924.886087
max      3361.977895
dtype: float64

In [93]:
df_clean[df_clean["Customer_ID"] == "C1521"][
    ["Customer_ID", "Tenure_Months", "Monthly_Charges", "Total_Charges"]
]

    Customer_ID  Tenure_Months  Monthly_Charges  Total_Charges
521       C1521            1.0              NaN        1705.68
528       C1521            1.0              NaN        1705.68

In [94]:
df_clean[
    (df_clean["Internet_Service"] == "Fiber") &
    (df_clean["Tenure_Months"] == 1)
][
    ["Customer_ID", "Subscription_Type", "Tenure_Months",
     "Monthly_Charges", "Total_Charges"]
]

,Customer_ID,Subscription_Type,Tenure_Months,Monthly_Charges,Total_Charges
218,C1218,Basic,1.0,1666.22,1714.22
393,C1393,Basic,1.0,2093.42,1966.42
436,C1436,Standard,1.0,379.70,772.70
521,C1521,NaN,1.0,NaN,1705.68
528,C1521,NaN,1.0,NaN,1705.68

In [95]:
df_clean[
    (df_clean["Internet_Service"] == "Fiber") &
    (df_clean["Tenure_Months"] == 1)
]["Monthly_Charges"].median()

np.float64(1666.22)

In [96]:
fiber_1month_median = df_clean[
    (df_clean["Internet_Service"] == "Fiber") &
    (df_clean["Tenure_Months"] == 1)
]["Monthly_Charges"].median()

In [97]:
df_clean["Monthly_Charges"] = df_clean["Monthly_Charges"].fillna(
    fiber_1month_median
)

In [98]:
df_clean["Monthly_Charges"].isna().sum()

np.int64(0)

In [99]:
# Total charges

In [100]:
df_clean[df_clean["Total_Charges"] < 0][
    ["Customer_ID", "Tenure_Months",
     "Monthly_Charges", "Total_Charges",
     "Subscription_Type", "Contract_Type"]
]

,Customer_ID,Tenure_Months,Monthly_Charges,Total_Charges,Subscription_Type,Contract_Type
17,C1017,48.0,1975.23,-94534.04,Basic,Month-to-Month
36,C1036,70.0,1285.52,-89554.40,Premium,Month-to-Month
94,C1094,43.0,2331.74,-99781.82,Premium,One Year
126,C1126,28.0,680.31,-18976.68,Standard,One Year
457,C1457,29.0,904.51,-25767.79,Basic,Month-to-Month

In [101]:
df_clean["Total_Charges"] = df_clean["Total_Charges"].abs()

In [102]:
df_clean[df_clean["Total_Charges"] < 0][
    ["Customer_ID", "Total_Charges"]
]

Empty DataFrame
Columns: [Customer_ID, Total_Charges]
Index: []

In [103]:
df_clean["Total_Charges"].describe()

count       533.000000
mean      50978.363246
std       40122.296422
min         354.120000
25%       19169.900000
50%       40952.260000
75%       75799.150000
max      171429.830000
Name: Total_Charges, dtype: float64

In [104]:
df_clean[df_clean["Total_Charges"].isna()][
    ["Customer_ID", "Tenure_Months", "Monthly_Charges",
     "Total_Charges", "Subscription_Type",
     "Contract_Type", "Churn"]
]

,Customer_ID,Tenure_Months,Monthly_Charges,Total_Charges,Subscription_Type,Contract_Type,Churn
9,C1009,30.0,1341.52,NaN,Basic,Month-to-Month,No
12,C1012,18.0,1722.85,NaN,Basic,One Year,Yes
160,C1160,64.0,2306.42,NaN,NaN,Two Year,Yes
249,C1249,63.0,1098.58,NaN,Basic,Month-to-Month,Yes
308,C1308,28.0,2195.67,NaN,Standard,One Year,No
368,C1368,22.0,1777.10,NaN,NaN,One Year,No
520,C1520,42.0,687.44,NaN,Premium,Month-to-Month,No
527,C1520,42.0,687.44,NaN,Premium,Month-to-Month,No
541,C5009,30.0,1341.52,NaN,Basic,Month-to-Month,No

In [105]:
calculated_total = df_clean["Monthly_Charges"] * df_clean["Tenure_Months"]

In [106]:
df_clean[df_clean["Total_Charges"].isna()][
    ["Customer_ID", "Monthly_Charges", "Tenure_Months", "Total_Charges"]
].assign(Calculated_Total=calculated_total)

,Customer_ID,Monthly_Charges,Tenure_Months,Total_Charges,Calculated_Total
9,C1009,1341.52,30.0,NaN,40245.60
12,C1012,1722.85,18.0,NaN,31011.30
160,C1160,2306.42,64.0,NaN,147610.88
249,C1249,1098.58,63.0,NaN,69210.54
308,C1308,2195.67,28.0,NaN,61478.76
368,C1368,1777.10,22.0,NaN,39096.20
520,C1520,687.44,42.0,NaN,28872.48
527,C1520,687.44,42.0,NaN,28872.48
541,C5009,1341.52,30.0,NaN,40245.60

In [107]:
df_clean["Total_Charges"] = df_clean["Total_Charges"].fillna(calculated_total)

In [108]:
df_clean["Total_Charges"].isna().sum()

np.int64(0)

In [109]:
# Tech_Support

In [110]:
df_clean["Tech_Support"].unique()

array(['Yes', 'No', nan], dtype=object)

In [111]:
df_clean["Tech_Support"].isna().sum()

np.int64(12)

In [112]:
df_clean[df_clean["Tech_Support"].isna()][
    ["Customer_ID", "Internet_Service", "Subscription_Type",
     "Contract_Type", "Tech_Support", "Churn"]
]

,Customer_ID,Internet_Service,Subscription_Type,Contract_Type,Tech_Support,Churn
17,C1017,Fiber,Basic,Month-to-Month,NaN,No
20,C1020,5G,Premium,Month-to-Month,NaN,No
38,C1038,Cable,Standard,Two Year,NaN,No
109,C1109,DSL,Basic,Two Year,NaN,No
126,C1126,Cable,Standard,One Year,NaN,Yes
180,C1180,Cable,Premium,One Year,NaN,No
237,C1237,Cable,Premium,Month-to-Month,NaN,Yes
310,C1310,Fiber,Premium,Month-to-Month,NaN,No
507,C1507,Fiber,Premium,Two Year,NaN,No
514,C1514,Cable,Premium,One Year,NaN,No
522,C1522,DSL,Premium,Month-to-Month,NaN,Yes
529,C1522,DSL,Premium,Month-to-Month,NaN,Yes

In [113]:
df_clean.groupby("Internet_Service")["Tech_Support"].value_counts()

Internet_Service  Tech_Support
5G                No              80
                  Yes             45
Cable             Yes             71
                  No              57
DSL               Yes             69
                  No              59
Fiber             Yes             72
                  No              70
Name: count, dtype: int64

In [114]:
df_clean.groupby("Subscription_Type")["Tech_Support"].value_counts()

Subscription_Type  Tech_Support
Basic              Yes             91
                   No              78
Premium            Yes             91
                   No              90
Standard           No              98
                   Yes             70
Name: count, dtype: int64

In [115]:
df_clean.groupby("Subscription_Type")["Tech_Support"].value_counts()

Subscription_Type  Tech_Support
Basic              Yes             91
                   No              78
Premium            Yes             91
                   No              90
Standard           No              98
                   Yes             70
Name: count, dtype: int64

In [116]:
df_clean.groupby("Subscription_Type")["Tech_Support"].agg(lambda x: x.mode()[0])

Subscription_Type
Basic       Yes
Premium     Yes
Standard     No
Name: Tech_Support, dtype: object

In [117]:
tech_support_mode = df_clean.groupby("Subscription_Type")["Tech_Support"].agg(
    lambda x: x.mode()[0]
)

In [118]:
df_clean["Tech_Support"] = df_clean["Tech_Support"].fillna(
    df_clean["Subscription_Type"].map(tech_support_mode)
)

In [119]:
df_clean["Tech_Support"].isna().sum()

np.int64(0)

In [120]:
# Dependents

In [121]:
df_clean["Dependents"].unique()

array(['Yes', 'No', nan], dtype=object)

In [122]:
df_clean["Dependents"].isna().sum()

np.int64(3)

In [123]:
df_clean[df_clean["Dependents"].isna()][
    ["Customer_ID", "Age", "Subscription_Type",
     "Contract_Type", "Dependents", "Churn"]
]

    Customer_ID   Age Subscription_Type Contract_Type Dependents Churn
12        C1012  35.0             Basic      One Year        NaN   Yes
518       C1518  47.0           Premium      One Year        NaN   Yes
525       C1518  47.0           Premium      One Year        NaN   Yes

In [124]:
# last interaction date

In [125]:
df_clean["Last_Interaction_Date"].isna().sum()

np.int64(3)

In [126]:
df_clean["Last_Interaction_Date"].unique()

array(['12-10-2025', '05-03-2026', '20-02-2026', '07-06-2026',
       '02-04-2026', '13-03-2026', '26-12-2025', '14-01-2025',
       '28-02-2025', '29-11-2025', '03-10-2025', '32/13/2025',
       '27-09-2025', '09-04-2025', '05-10-2025', '01-01-2026',
       '12-01-2026', '13-08-2025', '04-06-2025', '05-07-2025',
       '27-03-2025', '26-03-2026', '27-06-2026', '22-01-2026',
       '06-03-2026', '29-04-2026', '12-06-2026', '17-08-2025',
       '02-08-2025', '16-01-2025', '26-06-2026', '25-04-2026',
       '04-01-2026', '18-04-2026', '07-12-2025', '04-04-2025',
       '21-09-2025', '17-07-2025', '16-10-2025', '29-01-2026',
       '01-06-2026', '06-10-2025', '16-11-2025', '01-09-2025',
       '21-01-2025', '25-01-2026', '17-05-2026', '21-01-2026',
       '31-01-2025', '03-03-2026', '18-01-2025', '06-06-2026',
       '24-03-2026', '11-06-2025', '27-04-2026', '13-04-2026',
       '28-02-2026', '07-02-2026', '13-06-2026', '12-02-2025',
       '25-02-2025', '03-06-2025', '01-05-2026', '23-05-2025',
       '16-02-2026', '15-04-2026', '30-04-2026', '26-03-2025',
       '11-03-2025', '14-08-2025', '27-02-2026', '01-12-2025',
       '16-06-2026', '11-01-2025', '30-03-2025', '19-10-2025',
       '06-06-2025', '04-07-2026', '13-03-2025', '20-08-2025',
       '27-04-2025', '29-01-2025', '29-10-2025', '07-05-2025',
       '09-06-2026', '05-08-2025', '19-12-2025', '23-02-2025',
       '30-01-2025', '15-02-2026', '06-04-2025', '16-02-2025',
       '18-09-2025', '20-11-2025', '29-09-2025', '17-02-2025',
       '18-02-2026', '20-10-2025', '21-02-2025', '13-07-2025',
       '28-11-2025', '15-09-2025', '17-09-2025', '25-02-2026',
       '03-03-2025', '09-06-2025', '04-05-2026', '19-02-2025',
       '03-07-2025', '23-03-2025', '08-01-2026', '24-01-2025',
       '02-05-2026', '08-12-2025', '09-03-2026', '25-05-2026',
       '04-02-2025', '19-03-2026', '28-12-2025', '07-02-2025',
       '01-11-2025', '30-06-2025', '14-07-2025', '23-11-2025',
       '19-04-2026', '26-01-2026', '10-01-2026', '10-07-2025',
       '10-04-2026', '29-12-2025', '17-11-2025', '16-07-2025',
       '06-08-2025', '15-02-2025', '18-08-2025', '28-01-2026',
       '21-03-2026', '05-06-2026', '22-02-2025', '12-02-2026',
       '02-02-2026', '08-03-2025', '09-05-2026', '06-09-2025',
       '24-04-2025', '02-01-2026', '13-10-2025', '06-12-2025',
       '03-05-2026', '26-10-2025', '24-04-2026', '04-08-2025',
       '30-04-2025', '27-12-2025', '28-07-2025', '22-09-2025',
       '24-08-2025', '28-01-2025', '10-03-2026', '14-04-2026',
       '22-06-2025', '11-05-2025', '19-03-2025', '28-06-2026',
       '13-05-2026', '08-07-2025', '18-05-2026', '16-03-2026',
       '02-03-2025', '28-08-2025', '26-11-2025', '03-04-2025',
       '02-11-2025', '07-09-2025', '10-08-2025', '04-04-2026',
       '13-02-2025', '17-01-2025', '24-11-2025', '21-05-2026',
       '18-12-2025', '02-06-2025', '14-02-2025', '29-04-2025',
       '10-06-2025', '26-06-2025', '10-01-2025', '18-03-2025',
       '31-08-2025', '21-11-2025', '06-04-2026', '17-06-2025',
       '04-06-2026', '03-09-2025', '20-03-2026', '13-01-2025',
       '08-09-2025', '18-11-2025', '04-01-2025', '27-08-2025',
       '07-06-2025', '01-02-2026', '30-11-2025', '22-12-2025',
       '23-03-2026', '25-03-2025', '26-02-2026', '15-06-2025',
       '19-09-2025', '01-01-2025', '27-05-2026', '29-08-2025',
       '10-12-2025', '23-08-2025', '15-12-2025', '08-08-2025',
       '30-03-2026', '04-03-2025', '17-06-2026', '15-01-2025',
       '03-01-2025', '11-04-2025', '09-11-2025', '01-07-2025',
       '16-01-2026', '08-04-2026', '23-04-2025', '01-02-2025',
       '12-03-2026', '10-05-2026', '31-07-2025', '22-03-2026',
       '15-08-2025', '16-09-2025', '03-01-2026', '06-05-2025',
       '28-03-2025', '13-01-2026', '11-01-2026', '23-04-2026',
       '12-11-2025', '21-04-2026', '03-02-2026', '24-12-2025',
       '02-12-2025', '26-01-2025', '16-05-2025', '27-06-2025',
       '17-05-2025', '29-03-2025', '21-10-2025', '30-08-2025',
       '27-02-2025', '18-04-2025', '07-11-2025', '26-04-2026',
       '31-10-2025', '10-10-2025', '23-02-2026', '23-07-2025',
       '22-07-2025', '08-04-2025', '25-03-2026', '17-10-2025',
       '12-06-2025', '03-08-2025', '29-05-2026', '24-06-2026',
       '17-04-2025', '01-08-2025', '07-04-2025', '22-10-2025',
       '18-02-2025', '13-05-2025', '06-01-2026', nan, '10-02-2025',
       '25-06-2026', '14-04-2025', '28-04-2025', '16-05-2026',
       '10-02-2026', '20-05-2025', '19-07-2025', '15-11-2025',
       '29-05-2025', '15-03-2026', '03-06-2026', '31-12-2025',
       '11-11-2025', '18-07-2025', '10-11-2025', '05-11-2025',
       '19-01-2026', '08-06-2025', '03-12-2025', '02-05-2025',
       '12-07-2025', '03-02-2025', '08-11-2025', '27-05-2025',
       '24-02-2026', '17-01-2026', '19-02-2026', '11-10-2025',
       '29-06-2025', '24-03-2025', '19-06-2026', '12-05-2025',
       '31-05-2026', '28-10-2025', '21-06-2026', '14-11-2025',
       '26-09-2025', '30-05-2026', '21-02-2026', '31-01-2026',
       '15-07-2025', '30-10-2025', '06-05-2026', '13-12-2025',
       '15-04-2025', '11-02-2025', '30-09-2025', '30-05-2025',
       '30-01-2026', '18-01-2026', '08-10-2025', '02-02-2025',
       '21-06-2025', '07-10-2025', '25-01-2025', '06-03-2025'],
      dtype=object)

In [127]:
date_check = pd.to_datetime(
    df_clean["Last_Interaction_Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [128]:
date_check.isna().sum()

np.int64(4)

In [129]:
df_clean[date_check.isna()][
    ["Customer_ID", "Last_Interaction_Date"]
]

    Customer_ID Last_Interaction_Date
11        C1011            32/13/2025
382       C1382                   NaN
518       C1518                   NaN
525       C1518                   NaN

In [130]:
df_clean["Last_Interaction_Date"] = date_check

In [131]:
df_clean["Last_Interaction_Date"].dtype

dtype('<M8[ns]')

In [132]:
df_clean["Last_Interaction_Date"].isna().sum()

np.int64(4)

In [133]:
# resolving duplicates values

In [134]:
df_clean[df_clean["Customer_ID"].duplicated(keep=False)].sort_values("Customer_ID")

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
18,C1018,Amit Sharma,NaN,41.0,Gujarat,Ahmedabad,48.0,Premium,2328.32,111299.36,Month-to-Month,Net Banking,Fiber,Yes,No,Yes,No,2025-06-04
524,C1018,Anikta Sharma,Female,41.0,Gujarat,Ahmedabad,48.0,Premium,2328.32,111299.36,Month-to-Month,Net Banking,Fiber,Yes,No,Yes,No,2025-06-04
531,C1018,Anikta Sharma,Female,41.0,Gujarat,Ahmedabad,48.0,Premium,2328.32,111299.36,Month-to-Month,Net Banking,Fiber,Yes,No,Yes,No,2025-06-04
518,C1518,Vikas Yadav,Male,47.0,Maharashtra,Pune,1.0,Premium,2473.81,2618.81,One Year,Cash,NaN,No,No,NaN,Yes,NaT
525,C1518,Vikas Yadav,Male,47.0,Maharashtra,Pune,1.0,Premium,2473.81,2618.81,One Year,Cash,NaN,No,No,NaN,Yes,NaT
519,C1519,Unknown,Male,52.0,Karnataka,Bengaluru,39.0,Premium,718.22,27823.58,Month-to-Month,NaN,Fiber,Yes,No,Yes,No,2025-02-11
526,C1519,Unknown,Male,52.0,Karnataka,Bengaluru,39.0,Premium,718.22,27823.58,Month-to-Month,NaN,Fiber,Yes,No,Yes,No,2025-02-11
520,C1520,Pooja Singh,Male,69.0,UP,Lucknow,42.0,Premium,687.44,28872.48,Month-to-Month,Debit Card,Fiber,Yes,Yes,Yes,No,2025-11-21
527,C1520,Pooja Singh,Male,69.0,UP,Lucknow,42.0,Premium,687.44,28872.48,Month-to-Month,Debit Card,Fiber,Yes,Yes,Yes,No,2025-11-21
521,C1521,Mohit Arora,NaN,54.0,Karnataka,Bengaluru,1.0,NaN,1666.22,1705.68,NaN,Net Banking,Fiber,Yes,No,Yes,NaN,2025-01-10
528,C1521,Mohit Arora,NaN,54.0,Karnataka,Bengaluru,1.0,NaN,1666.22,1705.68,NaN,Net Banking,Fiber,Yes,No,Yes,NaN,2025-01-10
522,C1522,Mohit Arora,Female,49.0,UP,Kanpur,43.0,Premium,2140.60,92290.80,Month-to-Month,Net Banking,DSL,Yes,NaN,Yes,Yes,2025-08-15
529,C1522,Mohit Arora,Female,49.0,UP,Kanpur,43.0,Premium,2140.60,92290.80,Month-to-Month,Net Banking,DSL,Yes,NaN,Yes,Yes,2025-08-15
523,C1523,Sneha Jain,Male,36.0,Karnataka,Bengaluru,27.0,Standard,2436.13,65686.51,One Year,Debit Card,DSL,Yes,No,No,No,2025-03-23
530,C1523,Sneha Jain,Male,36.0,Karnataka,Bengaluru,27.0,Standard,2436.13,65686.51,One Year,Debit Card,DSL,Yes,No,No,No,2025-03-23

In [135]:
df_clean["Customer_ID"].duplicated().sum()

np.int64(8)

In [136]:
df_clean["Customer_ID"].nunique()

534

In [137]:
df_clean[df_clean["Customer_ID"].duplicated(keep=False)] \
    .sort_values("Customer_ID")

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
18,C1018,Amit Sharma,NaN,41.0,Gujarat,Ahmedabad,48.0,Premium,2328.32,111299.36,Month-to-Month,Net Banking,Fiber,Yes,No,Yes,No,2025-06-04
524,C1018,Anikta Sharma,Female,41.0,Gujarat,Ahmedabad,48.0,Premium,2328.32,111299.36,Month-to-Month,Net Banking,Fiber,Yes,No,Yes,No,2025-06-04
531,C1018,Anikta Sharma,Female,41.0,Gujarat,Ahmedabad,48.0,Premium,2328.32,111299.36,Month-to-Month,Net Banking,Fiber,Yes,No,Yes,No,2025-06-04
518,C1518,Vikas Yadav,Male,47.0,Maharashtra,Pune,1.0,Premium,2473.81,2618.81,One Year,Cash,NaN,No,No,NaN,Yes,NaT
525,C1518,Vikas Yadav,Male,47.0,Maharashtra,Pune,1.0,Premium,2473.81,2618.81,One Year,Cash,NaN,No,No,NaN,Yes,NaT
519,C1519,Unknown,Male,52.0,Karnataka,Bengaluru,39.0,Premium,718.22,27823.58,Month-to-Month,NaN,Fiber,Yes,No,Yes,No,2025-02-11
526,C1519,Unknown,Male,52.0,Karnataka,Bengaluru,39.0,Premium,718.22,27823.58,Month-to-Month,NaN,Fiber,Yes,No,Yes,No,2025-02-11
520,C1520,Pooja Singh,Male,69.0,UP,Lucknow,42.0,Premium,687.44,28872.48,Month-to-Month,Debit Card,Fiber,Yes,Yes,Yes,No,2025-11-21
527,C1520,Pooja Singh,Male,69.0,UP,Lucknow,42.0,Premium,687.44,28872.48,Month-to-Month,Debit Card,Fiber,Yes,Yes,Yes,No,2025-11-21
521,C1521,Mohit Arora,NaN,54.0,Karnataka,Bengaluru,1.0,NaN,1666.22,1705.68,NaN,Net Banking,Fiber,Yes,No,Yes,NaN,2025-01-10
528,C1521,Mohit Arora,NaN,54.0,Karnataka,Bengaluru,1.0,NaN,1666.22,1705.68,NaN,Net Banking,Fiber,Yes,No,Yes,NaN,2025-01-10
522,C1522,Mohit Arora,Female,49.0,UP,Kanpur,43.0,Premium,2140.60,92290.80,Month-to-Month,Net Banking,DSL,Yes,NaN,Yes,Yes,2025-08-15
529,C1522,Mohit Arora,Female,49.0,UP,Kanpur,43.0,Premium,2140.60,92290.80,Month-to-Month,Net Banking,DSL,Yes,NaN,Yes,Yes,2025-08-15
523,C1523,Sneha Jain,Male,36.0,Karnataka,Bengaluru,27.0,Standard,2436.13,65686.51,One Year,Debit Card,DSL,Yes,No,No,No,2025-03-23
530,C1523,Sneha Jain,Male,36.0,Karnataka,Bengaluru,27.0,Standard,2436.13,65686.51,One Year,Debit Card,DSL,Yes,No,No,No,2025-03-23

In [138]:
df_clean.duplicated().sum()

np.int64(7)

In [139]:
df_clean = df_clean.drop_duplicates()

In [140]:
df_clean.shape

(535, 18)

In [141]:
df_clean["Customer_ID"].duplicated().sum()

np.int64(1)

In [142]:
df_clean[df_clean["Customer_ID"] == "C1018"]

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
18,C1018,Amit Sharma,NaN,41.0,Gujarat,Ahmedabad,48.0,Premium,2328.32,111299.36,Month-to-Month,Net Banking,Fiber,Yes,No,Yes,No,2025-06-04
524,C1018,Anikta Sharma,Female,41.0,Gujarat,Ahmedabad,48.0,Premium,2328.32,111299.36,Month-to-Month,Net Banking,Fiber,Yes,No,Yes,No,2025-06-04

In [143]:
df_clean = df_clean[
    ~(
        (df_clean["Customer_ID"] == "C1018") &
        (df_clean["Customer_Name"] == "Amit Sharma")
    )
]

In [144]:
df_clean["Customer_ID"].duplicated().sum()

np.int64(0)

In [145]:
df_clean

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,Basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,2025-10-12
1,C1001,Rohit Kumar,Male,46.0,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,2026-03-05
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,2026-02-20
3,C1003,Unknown,Male,59.0,Karnataka,Bengaluru,55.0,Standard,1285.78,101349.10,Two Year,UPI,5G,No,No,Yes,No,2026-06-07
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,2026-04-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,C5005,Sneha Jain,Female,42.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,2026-03-13
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-to-Month,UPI,DSL,Yes,No,No,No,2025-12-26
539,C5007,Vikas Yadav,Male,61.0,Delhi,,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,2025-01-14
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,Basic,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,2025-02-28
541,C5009,Rahul Singh,Male,25.0,UP,Kanpur,30.0,Basic,1341.52,40245.60,Month-to-Month,Credit Card,Cable,No,No,Yes,No,2025-11-29

In [146]:
# missing values

In [147]:
df_clean["Gender"].isna().sum()

np.int64(4)

In [148]:
df_clean[df_clean["Gender"].isna()][
    ["Customer_ID", "Customer_Name", "Age", "State", "City",
     "Subscription_Type", "Contract_Type", "Churn", "Gender"]
]

,Customer_ID,Customer_Name,Age,State,City,Subscription_Type,Contract_Type,Churn,Gender
147,C1147,Vikas Yadav,62.0,Delhi,Unknown,Basic,Month-to-Month,No,NaN
232,C1232,Rahul Singh,46.0,Gujarat,Ahmedabad,Premium,One Year,No,NaN
456,C1456,Amit Sharma,47.0,Karnataka,Bengaluru,Premium,Two Year,No,NaN
521,C1521,Mohit Arora,54.0,Karnataka,Bengaluru,NaN,NaN,NaN,NaN

In [149]:
df_clean["Gender"] = df_clean["Gender"].fillna("Unknown")

In [150]:
df_clean["Gender"].isna().sum()

np.int64(0)

In [151]:
df_clean["Gender"].value_counts()

Gender
Female     270
Male       260
Unknown      4
Name: count, dtype: int64

In [152]:
df_clean["Subscription_Type"].isna().sum()

np.int64(11)

In [153]:
df_clean[df_clean["Subscription_Type"].isna()][
    ["Customer_ID", "Age", "Gender", "Tenure_Months",
     "Monthly_Charges", "Total_Charges",
     "Contract_Type", "Internet_Service", "Churn"]
]

,Customer_ID,Age,Gender,Tenure_Months,Monthly_Charges,Total_Charges,Contract_Type,Internet_Service,Churn
5,C1005,42.0,Female,1.0,1633.64,1707.64,Two Year,Cable,No
25,C1025,70.0,Male,42.0,1516.78,64151.76,Month-to-Month,Cable,No
56,C1056,41.0,Female,67.0,2193.44,146941.48,Month-to-Month,Fiber,No
72,C1072,18.0,Male,2.0,1914.24,3962.48,Two Year,NaN,Yes
143,C1143,24.0,Female,27.0,449.90,12606.30,Two Year,5G,No
160,C1160,67.0,Male,64.0,2306.42,147610.88,Two Year,5G,Yes
179,C1179,56.0,Female,1.0,1671.92,2065.92,One Year,DSL,No
238,C1238,60.0,Female,53.0,1022.84,53890.52,One Year,Cable,No
368,C1368,47.0,Male,22.0,1777.10,39096.20,One Year,Cable,No
521,C1521,54.0,Unknown,1.0,1666.22,1705.68,NaN,Fiber,NaN
537,C5005,42.0,Female,1.0,1633.64,1707.64,Two Year,Cable,No

In [154]:
df_clean["Subscription_Type"].value_counts()

Subscription_Type
Premium     183
Basic       171
Standard    169
Name: count, dtype: int64

In [155]:
subscription_mode = df_clean["Subscription_Type"].mode()[0]
subscription_mode

'Premium'

In [156]:
df_clean["Subscription_Type"] = df_clean["Subscription_Type"].fillna(subscription_mode)

In [157]:
df_clean["Subscription_Type"].isna().sum()

np.int64(0)

In [158]:
df_clean["Subscription_Type"].value_counts()

Subscription_Type
Premium     194
Basic       171
Standard    169
Name: count, dtype: int64

In [159]:
df_clean["Contract_Type"].isna().sum()

np.int64(3)

In [160]:
df_clean[df_clean["Contract_Type"].isna()][
    ["Customer_ID", "Subscription_Type", "Tenure_Months",
     "Monthly_Charges", "Total_Charges",
     "Internet_Service", "Churn"]
]

,Customer_ID,Subscription_Type,Tenure_Months,Monthly_Charges,Total_Charges,Internet_Service,Churn
57,C1057,Premium,72.0,1766.91,126942.52,5G,No
252,C1252,Basic,58.0,1633.30,94512.40,NaN,No
521,C1521,Premium,1.0,1666.22,1705.68,Fiber,NaN

In [161]:
df_clean["Contract_Type"].value_counts()

Contract_Type
Month-to-Month    195
One Year          174
Two Year          162
Name: count, dtype: int64

In [162]:
contract_mode = df_clean["Contract_Type"].mode()[0]
contract_mode

'Month-to-Month'

In [163]:
df_clean["Contract_Type"] = df_clean["Contract_Type"].fillna(contract_mode)

In [164]:
df_clean["Contract_Type"].isna().sum()

np.int64(0)

In [165]:
df_clean["Contract_Type"].value_counts()

Contract_Type
Month-to-Month    198
One Year          174
Two Year          162
Name: count, dtype: int64

In [166]:
df_clean["Payment_Method"].isna().sum()

np.int64(15)

In [167]:
df_clean[df_clean["Payment_Method"].isna()][
    ["Customer_ID", "Subscription_Type", "Contract_Type",
     "Monthly_Charges", "Total_Charges", "Churn"]
]

,Customer_ID,Subscription_Type,Contract_Type,Monthly_Charges,Total_Charges,Churn
8,C1008,Basic,Two Year,1200.00,75799.15,No
106,C1106,Basic,Month-to-Month,858.13,45930.02,No
161,C1161,Basic,Month-to-Month,1265.50,44319.50,No
237,C1237,Premium,Month-to-Month,1481.37,55080.69,Yes
282,C1282,Basic,Month-to-Month,2312.01,83596.36,No
329,C1329,Premium,Month-to-Month,620.87,13831.01,Yes
348,C1348,Basic,Two Year,2278.26,120609.78,No
364,C1364,Basic,Two Year,513.93,5329.23,Yes
370,C1370,Basic,Month-to-Month,1711.37,81760.76,Yes
400,C1400,Basic,Two Year,377.24,23440.12,No
436,C1436,Standard,Month-to-Month,379.70,772.70,No
437,C1437,Premium,Month-to-Month,873.54,1712.08,No
471,C1471,Standard,One Year,1927.08,67686.80,Yes
519,C1519,Premium,Month-to-Month,718.22,27823.58,No
540,C5008,Basic,Two Year,1200.00,75799.15,No

In [168]:
df_clean["Payment_Method"].value_counts()

Payment_Method
Debit Card     110
UPI            109
Cash           103
Credit Card     99
Net Banking     98
Name: count, dtype: int64

In [169]:
payment_mode = df_clean["Payment_Method"].mode()[0]
payment_mode

'Debit Card'

In [170]:
df_clean["Payment_Method"] = df_clean["Payment_Method"].fillna(payment_mode)

In [171]:
df_clean["Payment_Method"].isna().sum()

np.int64(0)

In [172]:
df_clean["Payment_Method"].value_counts()

Payment_Method
Debit Card     125
UPI            109
Cash           103
Credit Card     99
Net Banking     98
Name: count, dtype: int64

In [173]:
df_clean["Internet_Service"].isna().sum()

np.int64(6)

In [174]:
df_clean[df_clean["Internet_Service"].isna()][
    ["Customer_ID", "Subscription_Type", "Contract_Type",
     "Monthly_Charges", "Total_Charges", "Tenure_Months", "Churn"]
]

,Customer_ID,Subscription_Type,Contract_Type,Monthly_Charges,Total_Charges,Tenure_Months,Churn
72,C1072,Premium,Two Year,1914.24,3962.48,2.0,Yes
252,C1252,Basic,Month-to-Month,1633.30,94512.40,58.0,No
272,C1272,Standard,One Year,859.43,59798.10,70.0,No
419,C1419,Standard,Month-to-Month,1391.93,25357.74,18.0,Yes
450,C1450,Basic,One Year,714.58,7573.80,10.0,No
518,C1518,Premium,One Year,2473.81,2618.81,1.0,Yes

In [175]:
df_clean["Internet_Service"].value_counts()

Internet_Service
Fiber    140
Cable    133
DSL      129
5G       126
Name: count, dtype: int64

In [176]:
internet_mode = df_clean["Internet_Service"].mode()[0]
internet_mode

'Fiber'

In [177]:
df_clean["Internet_Service"] = df_clean["Internet_Service"].fillna(internet_mode)

In [178]:
df_clean["Internet_Service"].isna().sum()

np.int64(0)

In [179]:
df_clean["Internet_Service"].value_counts()

Internet_Service
Fiber    146
Cable    133
DSL      129
5G       126
Name: count, dtype: int64

In [180]:
df_clean["Senior_Citizen"].isna().sum()

np.int64(7)

In [181]:
df_clean[df_clean["Senior_Citizen"].isna()][
    ["Customer_ID", "Age", "Gender", "Subscription_Type",
     "Contract_Type", "Churn"]
]

    Customer_ID   Age  Gender Subscription_Type   Contract_Type Churn
73        C1073  53.0  Female           Premium  Month-to-Month    No
160       C1160  67.0    Male           Premium        Two Year   Yes
252       C1252  46.0    Male             Basic  Month-to-Month    No
254       C1254  51.0  Female             Basic  Month-to-Month    No
432       C1432  64.0    Male          Standard  Month-to-Month   Yes
474       C1474  45.0  Female          Standard  Month-to-Month    No
522       C1522  49.0  Female           Premium  Month-to-Month   Yes

In [182]:
df_clean["Senior_Citizen"].value_counts()

Senior_Citizen
No     424
Yes    103
Name: count, dtype: int64

In [183]:
senior_mode = df_clean["Senior_Citizen"].mode()[0]
senior_mode

'No'

In [184]:
df_clean["Senior_Citizen"] = df_clean["Senior_Citizen"].fillna(senior_mode)

In [185]:
df_clean["Senior_Citizen"].isna().sum()

np.int64(0)

In [186]:
df_clean["Senior_Citizen"].value_counts()

Senior_Citizen
No     431
Yes    103
Name: count, dtype: int64

In [187]:
df_clean[df_clean["Dependents"].isna()][
    ["Customer_ID", "Age", "Gender",
     "Subscription_Type", "Contract_Type",
     "Senior_Citizen", "Churn"]
]

,Customer_ID,Age,Gender,Subscription_Type,Contract_Type,Senior_Citizen,Churn
12,C1012,35.0,Female,Basic,One Year,No,Yes
518,C1518,47.0,Male,Premium,One Year,No,Yes

In [188]:
df_clean["Dependents"].value_counts()

Dependents
No     269
Yes    263
Name: count, dtype: int64

In [189]:
dependents_mode = df_clean["Dependents"].mode()[0]
dependents_mode

'No'

In [190]:
df_clean["Dependents"] = df_clean["Dependents"].fillna(dependents_mode)

In [191]:
df_clean["Dependents"].isna().sum()

np.int64(0)

In [192]:
df_clean["Dependents"].value_counts()

Dependents
No     271
Yes    263
Name: count, dtype: int64

In [193]:
df_clean["Churn"].isna().sum()

np.int64(3)

In [194]:
df_clean[df_clean["Churn"].isna()][
    ["Customer_ID", "Age", "Gender", "Tenure_Months",
     "Subscription_Type", "Contract_Type",
     "Monthly_Charges", "Total_Charges"]
]

,Customer_ID,Age,Gender,Tenure_Months,Subscription_Type,Contract_Type,Monthly_Charges,Total_Charges
158,C1158,35.0,Female,48.0,Premium,Month-to-Month,593.22,27997.56
513,C1513,41.0,Female,66.0,Basic,Month-to-Month,2491.79,164476.14
521,C1521,54.0,Unknown,1.0,Premium,Month-to-Month,1666.22,1705.68

In [195]:
df_clean = df_clean.dropna(subset=["Churn"])

In [196]:
df_clean["Churn"].isna().sum()

np.int64(0)

In [197]:
df_clean.isna().sum()

Customer_ID              0
Customer_Name            0
Gender                   0
Age                      0
State                    0
City                     0
Tenure_Months            0
Subscription_Type        0
Monthly_Charges          0
Total_Charges            0
Contract_Type            0
Payment_Method           0
Internet_Service         0
Tech_Support             0
Senior_Citizen           0
Dependents               0
Churn                    0
Last_Interaction_Date    3
dtype: int64

In [198]:
df_clean.shape

(531, 18)

In [199]:
df_clean[df_clean["Last_Interaction_Date"].isna()][
    ["Customer_ID", "Last_Interaction_Date", "Churn", "Tenure_Months"]
]

    Customer_ID Last_Interaction_Date Churn  Tenure_Months
11        C1011                   NaT    No           69.0
382       C1382                   NaT    No           31.0
518       C1518                   NaT   Yes            1.0

In [200]:
df_clean["Last_Interaction_Date"].isna().sum()

np.int64(3)

In [201]:
df_clean["Last_Interaction_Date"].min(), df_clean["Last_Interaction_Date"].max()

(Timestamp('2025-01-01 00:00:00'), Timestamp('2026-07-04 00:00:00'))

In [202]:
df_clean["Last_Interaction_Date"].dtype

dtype('<M8[ns]')

In [203]:
# Done with all the cleaning , cheaking one last time

In [204]:
df_clean[df_clean["Age"] < 18][["Customer_ID", "Age"]]

Empty DataFrame
Columns: [Customer_ID, Age]
Index: []

In [205]:

df_clean[df_clean["Age"] > 100][["Customer_ID", "Age"]]

Empty DataFrame
Columns: [Customer_ID, Age]
Index: []

In [206]:
df_clean[df_clean["Tenure_Months"] <= 0][
    ["Customer_ID", "Tenure_Months"]
]

Empty DataFrame
Columns: [Customer_ID, Tenure_Months]
Index: []

In [207]:
df_clean[df_clean["Monthly_Charges"] < 0][
    ["Customer_ID", "Monthly_Charges"]
]

Empty DataFrame
Columns: [Customer_ID, Monthly_Charges]
Index: []

In [208]:
df_clean[df_clean["Total_Charges"] < 0][
    ["Customer_ID", "Total_Charges"]
]

Empty DataFrame
Columns: [Customer_ID, Total_Charges]
Index: []

In [209]:
df_clean["Gender"].value_counts()

Gender
Female     268
Male       260
Unknown      3
Name: count, dtype: int64

In [210]:
df_clean["Subscription_Type"].value_counts()

Subscription_Type
Premium     192
Basic       170
Standard    169
Name: count, dtype: int64

In [211]:
df_clean["Contract_Type"].value_counts()

Contract_Type
Month-to-Month    195
One Year          174
Two Year          162
Name: count, dtype: int64

In [212]:
df_clean["Contract_Type"].value_counts()

Contract_Type
Month-to-Month    195
One Year          174
Two Year          162
Name: count, dtype: int64

In [213]:
df_clean["Payment_Method"].value_counts()

Payment_Method
Debit Card     124
UPI            108
Cash           103
Credit Card     99
Net Banking     97
Name: count, dtype: int64

In [214]:
df_clean["Internet_Service"].value_counts()

Internet_Service
Fiber    144
Cable    132
DSL      129
5G       126
Name: count, dtype: int64

In [215]:
df_clean["Tech_Support"].value_counts()

Tech_Support
No     273
Yes    258
Name: count, dtype: int64

In [216]:
df_clean["Senior_Citizen"].value_counts()

Senior_Citizen
No     428
Yes    103
Name: count, dtype: int64

In [217]:
df_clean["Dependents"].value_counts()

Dependents
No     270
Yes    261
Name: count, dtype: int64

In [218]:
df_clean["Churn"].value_counts()

Churn
No     404
Yes    127
Name: count, dtype: int64

In [219]:
df_clean["Customer_ID"].duplicated().sum()

np.int64(0)

In [220]:
df_clean["Customer_ID"].nunique()

531

In [221]:
df_clean.shape

(531, 18)

In [222]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 531 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            531 non-null    object
 1   Customer_Name          531 non-null    object
 2   Gender                 531 non-null    object
 3   Age                    531 non-null    float64
 4   State                  531 non-null    object
 5   City                   531 non-null    object
 6   Tenure_Months          531 non-null    float64
 7   Subscription_Type      531 non-null    object
 8   Monthly_Charges        531 non-null    float64
 9   Total_Charges          531 non-null    float64
 10  Contract_Type          531 non-null    object
 11  Payment_Method         531 non-null    object
 12  Internet_Service       531 non-null    object
 13  Tech_Support           531 non-null    object
 14  Senior_Citizen         531 non-null    object
 15  Dependents             531 non-null    object
 16  Churn                  531 non-null    object
 17  Last_Interaction_Date  528 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(4), object(13)
memory usage: 78.8+ KB

In [223]:
# Exporting clean data file

In [224]:
# df_clean.to_excel('clean_data.xlsx', index=False)